---
 - name: Check the service status 
   hosts: all
   gather_facts: false
   tasks:
     - name: check the {{ service_name }} service 
       shell: ps -ef | grep -v grep | grep {{service_name }}
       changed_when: false
       register: output
       ignore_errors: true

     - name: display the output
       debug:
         msg: " Service {{ service_name }} is not found "
       when: output.rc == 1
     - name : Display the output 
       debug:
         msg: "service {{ service_name}} is running" 
       when: output.rc == 0
